### ISSUE TITLE
Adding .landscape.yaml break build

### ISSUE THREAD

**Issue by revesansparole** [landscapeio/landscape-issues#190] opened 2015-10-30 19:57 UTC
Package working nicely.
Adding .landscape.yaml at the root of directory break build
Removing the yaml file and the build is passing again

In both case the build is successfull on Travis

Config is not taken from setup.cfg or tox.ini either

**Comment by carlio** [comment] 2015-11-07 23:45
@revesansparole This is now fixed, it was caused by an unrelated error when sending mail. You should be able to add the `.landscape.yaml` back now

**Closed as completed by carlio** 2015-11-07 23:45 UTC

**Comment by revesansparole** [comment] 2015-11-08 19:54
seems to work now, thanks
