### ISSUE TITLE
Landscape generates invalid MD link for badge

### ISSUE THREAD

**Issue by rafalp** [landscapeio/landscape-issues#26] opened 2014-01-22 13:49 UTC
Landscape allows me to make badge to put on my repo which is nice (everybody loves badges ;)), but link it gives you to use for MD documents is something like this:

```
[![Code Health](landscape.io/github/rafalp/Misago/future/landscape.png)](landscape.io/github/rafalp/Misago/future)
```

This link looks like this on Github:
[![Code Health](landscape.io/github/rafalp/Misago/future/landscape.png)](landscape.io/github/rafalp/Misago/future)

Code maker should prepend "https://" to landscape.io

**Comment by carlio** [comment] 2014-01-25 11:39
Caused by the same thing as #27. Fixed now, thanks!

**Closed as completed by carlio** 2014-01-25 11:39 UTC
