### ISSUE TITLE
Disable landscape-bot?

### ISSUE THREAD

**Issue by astrofrog** [landscapeio/landscape-issues#109] opened 2015-02-06 08:08 UTC
I can't seem to be able to disable the landscape bot which started commenting on all PRs yesterday. How do I do this?

**Comment by carlio** [comment] 2015-02-06 08:24
@astrofrog Which repository or organisation? You should be able to turn it off via the settings here: https://landscape.io/preferences/

**Comment by astrofrog** [comment] 2015-02-06 09:02
@carlio - I see the preference but no way to change it:

![screen shot 2015-02-06 at 10 01 50 am](https://cloud.githubusercontent.com/assets/314716/6076704/387afba8-ade7-11e4-8cdc-afda69f14ef9.png)

**Comment by carlio** [comment] 2015-02-06 09:04
@astrofrog Oh, my apologies. There should be a checkbox there. It does exist for me, so I'm not quite sure what the problem is, I will investigate.

**Comment by carlio** [comment] 2015-02-06 09:04
@astrofrog In the mean time I will turn off the pull requests for astropy myself.

**Comment by astrofrog** [comment] 2015-02-06 09:04
@carlio - thanks!

**Comment by carlio** [comment] 2015-04-03 11:15
Closed as duplicate of #122

**Closed as completed by carlio** 2015-04-03 11:15 UTC
