### ISSUE TITLE
Can't check repositories to add them

### ISSUE THREAD

**Issue by mplewis** [landscapeio/landscape-issues#64] opened 2014-08-04 22:22 UTC
When I try to add a repo to track, I see the following:

![landscape hosted continuous python code metrics](https://cloud.githubusercontent.com/assets/1829094/3804404/b0e025d6-1c25-11e4-8883-875815da5e8b.png)

Am I missing something? I don't know how to tell Landscape which repositories I want to track. I get an error when I click the Add Repositories button:

> You haven't selected any repositories to be checked. Please select some below to get started with Landscape.

**Comment by carlio** [comment] 2014-08-05 06:22
Hi @mplewis - You just need to click the names of the repositories you want to check, they will turn green to show they're selected.

**Comment by mplewis** [comment] 2014-08-05 06:30
That doesn't seem to do anything for me. Additionally, I'm seeing the following in `landscape.io/repository/add`:

![screenshot 2014-08-04 23 29 20](https://cloud.githubusercontent.com/assets/1829094/3807620/ec7f7666-1c69-11e4-8806-0668ce3f1d61.png)

The errors continue to add up about six per second.

**Comment by carlio** [comment] 2014-08-05 06:31
Oh. Seems like my dodgy javascript caught up to me! I'll see if I can figure out what's going on, thanks for the help.

**Comment by carlio** [comment] 2014-08-05 07:00
Could you do me a huge favour and send me the HTML? I can't seem to reproduce this locally. If you could email it to contact@landscape.io I would be very greatful!

**Comment by mplewis** [comment] 2014-08-05 07:12
Sure thing! Emailed.

**Comment by carlio** [comment] 2014-08-05 07:35
Brilliant, thank you. That made it much easier to debug. It turns out that the repository owned by user '4950' was causing the problem - JavaScript assumed it was an int, and therefore the `.indexOf` function wasn't available. My kingdom for strong types.

I just pushed a fix, hopefully it will work for you now.

**Closed as completed** 2014-08-07 09:03 UTC

**Comment by mplewis** [comment] 2014-08-07 21:17
Verifying that this works. Thanks! :+1:
