### ISSUE TITLE
Prospector execution failed - maybe more logs is needed

### ISSUE THREAD

**Issue by aldor007** [landscapeio/landscape-issues#95] opened 2014-11-23 20:59 UTC
Hi
I have error "Prospector execution failed" with project [Teleinformatyka/RedSparrow](https://landscape.io/github/Teleinformatyka/RedSparrow/24). I was trying to add/delete .landscape.yaml but with no luck - it's still not working. Maybe you should consider provide more logs about prospector fail, because i think it can be fixed in my project by config file.

**Comment by pennyarcade** [comment] 2014-11-24 16:43
Hi,

Same Problem here. My tests are failing since 3 days. I had Prospector errors as well as container failures. Please help soon since this is blocking my development.

Regards, Martin

**Comment by carlio** [comment] 2014-11-24 21:29
@Aldor007 - I had a look at the crashes for your repository, it turns out to be a failure in reading the non-ascii filenames. This is a bug in how Landscape sets up the locale for the environment for checking (defaults to ascii only apparently), so I'll look into fixing it ASAP.

@pennyarcade - your issue is due to a bug in pep8 - if you try running pep8 on your codebase, you'll see the stack trace! I've created a pull request on your repository to fix the issue. It's not perfect, but a real fix will require getting a bugfix merged into pep8 which will take a while. https://github.com/pennyarcade/py_pov/pull/1 . Note that the real problem is probably this line: https://landscape.io/github/carlio/py_pov/1/modules/lgeo/include/brick/lg_2441.py#L1053  - there is a missing `(` after `Box` which is also causing mccabe to fail!

**Comment by pennyarcade** [comment] 2014-11-25 08:45
Hello Carl,

 

thanks so much for pointing this out. My bad. Sorry for causing you avoidable work.

 

Regards, Martin

 

Gesendet: Montag, 24. November 2014 um 22:29 Uhr
Von: "Carl Crowder" notifications@github.com
An: landscapeio/landscape-issues landscape-issues@noreply.github.com
Cc: pennyarcade chocokiko4@gmx.de
Betreff: Re: [landscape-issues] Prospector execution failed - maybe more logs is needed (#95)

@Aldor007 - I had a look at the crashes for your repository, it turns out to be a failure in reading the non-ascii filenames. This is a bug in how Landscape sets up the locale for the environment for checking (defaults to ascii only apparently), so I'll look into fixing it ASAP.

@pennyarcade - your issue is due to a bug in pep8 - if you try running pep8 on your codebase, you'll see the stack trace! I've created a pull request on your repository to fix the issue. It's not perfect, but a real fix will require getting a bugfix merged into pep8 which will take a while. pennyarcade/py_pov#1 . Note that the real problem is probably this line: https://landscape.io/github/carlio/py_pov/1/modules/lgeo/include/brick/lg_2441.py#L1053 - there is a missing ( after Box which is also causing mccabe to fail!

**Comment by aldor007** [comment] 2014-11-27 22:12
@carlio 
:+1: 
Thanks for taking the time to find the problem. I look forward to when this will be fixed, but without haste.

**Comment by aldor007** [comment] 2014-12-05 19:51
hi
Any progress to resolve this issue?
@carlio

**Comment by blueyed** [comment] 2015-04-29 04:51
Logs and/or extended information/output would be really useful in this case.

E.g. on https://landscape.io/github/yourlabs/django-autocomplete-light/5 it just says:

```
Oh No

Check number 5 has failed. This is almost always due to a bug in Landscape - we have been notified. Sorry about that.
Failure reason: Prospector execution failed

The checking tool, prospector, did not complete correctly
```

Running prospector 0.10.1 locally in this repo does not cause a crash or something similar.

**Comment by carlio** [comment] 2015-04-29 12:37
@blueyed I investigated, turns out that pylint/astroid is crashing when trying to infer some types. Strange that it doesn't fail locally though. I'll do a local checkout and try to reproduce; could you tell me what versions of the following libs you have installed? Thanks!

pylint, astroid, logilab-common, pylint-django

**Comment by carlio** [comment] 2015-04-29 12:50
Ah, never mind - latest of everything crashes locally too. You need to use the `--die-on-tool-error` flag to prospector to see the error, otherwise it's a bit "hidden" amongst the other messages. It's something deep in astroid so it's not something I can directly fix unfortunately. I'll see if I can figure out and submit a patch to the pylint folks.

**Comment by mistercrunch** [comment] 2016-03-20 16:07
<img width="818" alt="screen shot 2016-03-20 at 9 04 46 am" src="https://cloud.githubusercontent.com/assets/487433/13905368/f662afce-ee7a-11e5-8d07-4719ab45a87e.png">
I'm also left in the dark with a failure, with little indications or hints. I'm not sure how to reproduce locally with prospector but that's what I'm attempting next...

**Closed as completed** 2019-12-31 17:40 UTC
