### ISSUE TITLE
Completely unrelated file being blamed for "Cyclic import" pylint warning

### ISSUE THREAD

**Issue by edmorley** [landscapeio/landscape-issues#159] opened 2015-05-30 16:12 UTC
A file is being blamed for cyclic imports, when it doesn't import any of the modules listed?

ie:
https://landscape.io/github/mozilla/treeherder/1633/modules/deployment/update/update.py#L1

"Cyclic import (treeherder.etl.perf_data_adapters -> treeherder.model.tasks -> treeherder.model.derived.jobs -> treeherder.model.derived.artifacts)"

When (a) none of those modules are imported by update.py, and (b) update.py isn't even listed in the cycle.

I can't reproduce this locally with Pylint - is this just a rendering issue with landscape.io showing where the issues were found?

**Comment by edmorley** [comment] 2015-05-30 17:00
I've since added that file to .landscape.yaml ignore-paths, and now those warnings have moved to a different, but still unrelated file:
https://landscape.io/github/mozilla/treeherder/1635/modules/puppet/files/treeherder/local.vagrant.py#L1

**Comment by spaceone** [comment] 2015-06-09 23:28
I have the same issue on an empty file: https://landscape.io/github/spaceone/httoop/17/modules/httoop/cache/__init__.py#L1

**Comment by psav** [comment] 2015-11-10 21:10
Same issue reported here too https://landscape.io/github/RedHatQE/cfme_tests/33/modules/sprout/manage.py#L1

**Comment by stefano-maggiolo** [comment] 2015-11-27 07:29
Another example: https://landscape.io/github/stefano-maggiolo/cms/126/modules/cmscommon/eventsource.py

Is this issue being looked into?

**Comment by mistercrunch** [comment] 2016-03-16 19:22
+1

**Comment by zebpalmer** [comment] 2016-05-06 16:23
fwiw, I found this issue thread searching for the same problem that I'm seeing in Wing (not using landscape on this). It appears this bug is in pylint itself.  

see http://stackoverflow.com/questions/30656388/pylint-reporting-cyclic-import-on-file-without-imports for possible explanation.

**Comment by carlio** [comment] 2016-06-18 06:47
This has been a bugbear for a while so I'll close this as duplicate of https://github.com/landscapeio/landscape-issues/issues/214 to keep it all in one place.

**Closed as completed by carlio** 2016-06-18 06:47 UTC
