### ISSUE TITLE
Radio Buttons not Rendering in Chrome

### ISSUE THREAD

**Issue by cancan101** [landscapeio/landscape-issues#166] opened 2015-07-01 07:09 UTC
![image](https://cloud.githubusercontent.com/assets/51059/8449324/896e42e4-1f9e-11e5-8306-62c23993ae53.png)

**Comment by carlio** [comment] 2015-07-25 19:25
I think this is fixed now. Could you please check? I'm unable to reproduce but several people have reported it so it'd be really helpful if you could let me know! @cancan101

**Closed as completed by carlio** 2015-07-25 19:25 UTC

**Comment by cancan101** [comment] 2015-07-27 14:23
This appears to be fixed.
